#! /usr/bin/env python
for i in `seq 0 4`; do
    for rep in `seq 2`; do
        OUT_PATH=artifacts_harmonic_${i}/rep_${rep}
        python ~/harm2d/segmentation.py dataset $OUT_PATH harmonic train -j 1 \
        -b 4 --epochs 50 -i $i
    done
done
