#!/usr/bin/env bash
DATA=/cvlabdata2/cvlab/datasets_tyszkiewicz/drive
python tournament.py $DATA artifacts_tournament_dropout -b 3 -j 4 --bloat 750 --epochs 50 --lr 1e-2 --optimize --num-contestants 20 --num-round 4 
