#! /usr/bin/env bash
DATA=/cvlabdata2/cvlab/datasets_tyszkiewicz/isic2018/test/imgs/
ART=/cvlabdata2/home/tyszkiew/full_size_iou
LOAD=edge_loss_isic_f1/harmonic/epoch59.pth.tar
B=2
J=4
python process.py $DATA $ART $LOAD harmonic -j $J
