#! /usr/bin/env bash
python main.py /cvlabdata2/cvlab/datasets_tyszkiewicz/isic2018 artifacts_relax harmonic train --lr 1e-3 -b 1 -j 1 --epochs 5
python main.py /cvlabdata2/cvlab/datasets_tyszkiewicz/isic2018 artifacts_relax harmonic train --lr 1e-3 -b 1 -j 1 --epochs 25 --load artifacts_relax/epoch4.pth.tar
