#! /usr/bin/env bash
DATA=/cvlabdata2/cvlab/datasets_tyszkiewicz/deepglobe/train
ART=artifacts_unconstrained
python main.py $DATA $ART unconstrained train --lr 1e-2 -b 2 -j 3 --epochs 35 --logdir=$ART/tb/unconstrained --optimize --load artifacts_harmonic_resume/epoch25.pth.tar
